version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: oracle_postgres
    environment:
      POSTGRES_USER: oracle
      POSTGRES_PASSWORD: oracle
      POSTGRES_DB: oracle
    ports:
      - "5434:5432"
    volumes:
      - oracle-postgres:/var/lib/postgresql/data

volumes:
  oracle-postgres:
